---


- stat: path=/usr/bin/atom
  register: atom_stat
  when: editors.atom

- name: Downloading atom
  get_url: url=https://atom.io/download/rpm dest=/tmp/atom.rpm force=yes
  when: editors.atom and not atom_stat.stat.exists

- name: Installing atom
  yum: name=/tmp/atom.rpm state=latest
  when: editors.atom and not atom_stat.stat.exists
