---
  #
  ####################
  ## Install firefox (updated)
  ####################
  - stat: path=/opt/firefox/firefox
    register: firefox_stat
  
  - name: Downloading firefox
    get_url: 
        url=https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US 
        dest=/tmp/firefox.tgz
    when: not firefox_stat.stat.exists

  - name: Extract firefox.tgz into /opt
    unarchive:
        src:  /tmp/firefox.tgz
        dest: /opt
    when: not firefox_stat.stat.exists

  - name: Removing old firefox
    file: 
       path: /usr/bin/firefox
       state: absent
          
  - name: Setting up link
    file: 
       src: /opt/firefox/firefox
       dest: /usr/bin/firefox
       state: link
