---

#- name: Install PPAs
#  apt_repository: repo={{item}} update_cache=yes
#  with_items:
#    - ppa:git-core/ppa
#

- name: Install Dev repos (yum install)
  yum: name={{item}}
  with_items:
  - http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm

- name: Install Packages
  yum: name={{item}}
  with_items:
    - git
    - meld

      ##- name: Install Rust
      ##  apt_repository: repo={{item}} update_cache=yes
      ##  with_items:
      ##    - ppa:git-core/ppa



