---
#- name: Install PPAs
#  apt_repository: repo={{item}} update_cache=yes
#  with_items:
          #- ppa:apt-fast/stable
          #  - ppa:libreoffice/ppa
          #  - ppa:webupd8team/terminix
          #  - ppa:ultradvorka/ppa
  ##      - ppa:tmsu/ppa

- name: Install Packages
  yum: name={{item}} state=latest # update_cache=yes
  with_items:
  - mosh
